### ISSUE TITLE
Tests fails on readLine()

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#105]
```
val `is` = InputStreamReader(ByteArrayInputStream(byteArrayOf('A'.toByte(), 'B'.toByte(), 0xC3.toByte(), 0xA1.toByte())))
println("readLine:" + BufferedReader(`is`).readLine())
```
This code not working, readLine have hard code with encoding. Java and Haxe have differnt implementation.

**Comment by soywiz** [comment]
I had issues with encodings in windows in some targets:

https://github.com/jtransc/jtransc/blob/920ae75b87dce6692df88d8311beb76553bf8907/jtransc-utils/src/com/jtransc/io/processutils.kt#L170

Maybe the problem is related to that? Try to check if that line reaches and try changing values.

Maybe is related to other thing?
I have tried the testcase in nodejs and it seems to work.

**Comment by SergeyLabutin** [comment]
JsTest > testIssue105 FAILED
    org.junit.ComparisonFailure at JsTest.kt:225

org.junit.ComparisonFailure: expected:<readLine:AB[ГЎ]> but was:<readLine:AB[á]>

**Comment by soywiz** [comment]
Can you open a cmd and execute "chcp" command?

```
Microsoft Windows [Versión 10.0.15063]
(c) 2017 Microsoft Corporation. Todos los derechos reservados.

C:\Users\soywiz>chcp
Página de códigos activa: 850

C:\Users\soywiz>
```

I have the codepage 850. Which one do you have?

**Comment by soywiz** [comment]
Ok. So for what I have seen the code page 866 is single character for cyrillic.
https://en.wikipedia.org/wiki/Code_page_866

It seems that it is reading as 850 or something. For me it produces:
```
readLine:ABá
```

Maybe the problem is this:
https://github.com/jtransc/jtransc/blob/920ae75b87dce6692df88d8311beb76553bf8907/jtransc-rt/src/java/nio/charset/Charset.java#L126

The defaultCharset in JTransc is UTF-8

**Comment by SergeyLabutin** [comment]
I think this best way
> or just implement a mapping from JAVA
We have russian settings, but 100% china or corea have problems and this check very hard. Java logic will be best for convert tool from java language ;)

**Comment by soywiz** [comment]
Ok. So here is my proposal:

I will try to embed most common single-byte charsets in jtransc-rt. I will start adding CP850+CP866.

Since charsets are accessed dynamically I have to include them as long as Charset is used.

Some CJK charsets like Japanese SHIFT-JIS (I'm familiar with this one) are multi-byte and have to hold tons of ideograms, which make conversion tables huge. And nowadays most projects use UTF-8.

So to prevent growing too much in client-side targets like javascript with multibyte charsets, I would evaluate two options for this issue:

* Try to use i18n extensions from javascript, changing the body that registers Charsets to use i18n ( http://caniuse.com/internationalization - https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Intl )
* Add a new project called jtransc-rt-extended-charsets. So in gradle you add dependencies `{ jtransc "com.jtransc:jtransc-rt-extended-charsets:$jtranscVersion" }` when requiring extended charsets other than UTF-8 + popular. That would just include that dependency when compiling to jtransc, that would effectively add new charsets using ServiceLoader internally and automatically.

In my case for example since all my code is new, I'm just using UTF-8 and don't need additional charsets.

**Comment by soywiz** [comment]
I have added a new Charset system using ServiceLoader per charset. Also I have added the possibility to disable some services in gradle with skipServiceLoader
https://github.com/jtransc/jtransc/commit/7f0ed1cef8a133266386303fd4d297c826228eeb

**Comment by SergeyLabutin** [comment]
I bad in character encodincs, but i find next strange:

1. if i make change in any file in jtransc and back, system see as file changed and only revert can show no changes, maybe java files have incorrect incoding?

![image](https://cloud.githubusercontent.com/assets/16681137/25308877/99956714-27c7-11e7-9ccc-509d282d747b.png)
i open in notepad++ and try find in non modified CharsetIBM
![image](https://cloud.githubusercontent.com/assets/16681137/25308878/a20e6472-27c7-11e7-927d-297c5da067e7.png)
![image](https://cloud.githubusercontent.com/assets/16681137/25308910/1ecf2bf4-27c8-11e7-8c8e-f4cd89e0d34f.png)

P.S. This maybe not problem, i'am not understand how it work =)

**Comment by SergeyLabutin** [comment]
Maybe it hack but looks as good workarround.
In `~/.gradle/gradle.properties` add jvmargs for all project compile (jtransc/backend/our project)
`-Dfile.encoding=UTF-8`
And for oom problems `-Xmx5G`
Maybe need add to Readme default settings, or maybe need add this settings to project level, i not known as better.
Now my default jvmargs is
`org.gradle.jvmargs=-d64 -Xmx5G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="~/.gradle/oom.dump" -Dfile.encoding=UTF-8`

With this testIssue105 is pass.

**Comment by soywiz** [comment]
I will have to check whether it is possible to reduce memory usage.
I wanted to be able to serialize the AST. That way i would be able load classes one by one. And decode methods just when required. That would help a lot. Right now the whole graph is in memory. Including method bodies. I will try to do that optimization after 1.0. Even when no persisting in disk, that would help.
For now maybe we could check if there is garbage holded anywhere that could be offloaded. But still if you have tons of classes probably the problem is that.
