### ISSUE TITLE
Problem with antivirus

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#109]
I write in readme about it. After update windows problem return. This not jtransc problem, but maybe write for new developers. It's Windows Defender, but Comodo in previous time detect too, now i mark folder for him.

![image](https://cloud.githubusercontent.com/assets/16681137/25302851/33b820ac-2750-11e7-9f45-7e0a86040928.png)

**Comment by soywiz** [comment]
```
https://haxe.org/download/version/3.4.0/
```
---
```
https://haxe.org/download/file/3.4.0/haxe-3.4.0-win.zip/
```
---
```
https://github.com/HaxeFoundation/haxe/releases/download/3.4.0/haxe-3.4.0-win.zip
```
---
```bash
wget https://github.com/HaxeFoundation/haxe/releases/download/3.4.0/haxe-3.4.0-win.zip
sha256sum haxe-3.4.0-win.zip
9e9963ff3d166593efd736d3045863098391d94406ddb40898cc79307f1a06d4  haxe-3.4.0-win.zip
```
---

https://www.virustotal.com/es/file/9e9963ff3d166593efd736d3045863098391d94406ddb40898cc79307f1a06d4/analysis/1492860952/

https://www.virustotal.com/es/url/867e6a7d842d27b252cfd467378912dc5302ee2c7fb411f63c7824184eec1dfe/analysis/1492860948/

---
Please calculate the sha256 of the zip file (haxe-3.4.0-win.zip) that you downloaded and check that matches.
Also maybe you are infected with other undetected virus/trojan that modifies executables in order to infect them.
I think that reporting this here could be misleading to other users. First you should verify that indeed the downloaded file is infected; with other computer or online antivirus. You should also verify hashes with other sources. If it was indeed infected, you should report to Haxe/or an antivirus company to check whether this is a false positive in this case instead of here. Af far as I know nobody never reported Haxe as harmful.
---
Think that reporting things like this could end harming reputation, either for the project or your own, so please check twice again before reporting it to Haxe.

Thanks for you understanding.
