### ISSUE TITLE
Support for Overlay

### ISSUE THREAD

**Issue by marciodel** [jtransc/jtransc#139]
It would be nice to have a Overlay implementation, so a JTranscNativeName annotated class could also have some implementations visible only to java.

For classes, the non native and non abstract (static or instance) methods could be considered as Overlay methods. It would be nice to support overlay methods in pure java or annotated with JTranscMethodBody.

For interfaces, the non native static and default (defenders) methods should be considered as Overlay methods. It would be nice to support overlay methods in pure java or annotated with JTranscMethodBody.

It is also a nice to have, to implement Overlay fields.

**Comment by soywiz** [comment]
I think I'm going to implement this as an integrated plugin so it will work for all targets, and not required extra work for any target.
The idea is to create a static class for static method and move there these methods and update all call-sites to those methods.

In the case of fields. I think it could work out of the box on JS since you can add fields. But definitely won't work on other targets.
