### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x16fc632d8)

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#165]
line where mark as bad in ProgramReflection_AllClasses_.cpp
```
 ::JA_L ProgramReflection_AllClasses__obj::getAllClasses___Lj_ClassInfo_(){ <<< HERE
HX_GC_STACKFRAME(&_hx_pos_851467f9a8a026f2_13_getAllClasses___Lj_ClassInfo_)
```

in output warning
```
[DYMTLInitPlatform] platform initialization successful
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb)
```

Please, help me with this error. It's critical for my project =(

**Comment by soywiz** [comment]
Is it related to #164?
I can try help you. But I need to reproduce it. How can I trigger the issue?

**Comment by SergeyLabutin** [comment]
Also in stacktrace i see main class with initialize statics ::SI() with 8053 lines
```
void JtranscMain_EntryPoint__obj::__construct(){
...
HXLINE(4148)		::java_::lang::AssertionError__obj::SI();
HXLINE(4149)		::com::jtransc::JTranscSystem__obj::SI();
HXLINE(4150)		::my::util::lang::GenericBean__obj::SI(); <<< HERE
```

**Comment by SergeyLabutin** [comment]
Additional: i'am use debugIos for compile on iPad device, with debugHaxecpp on mac all is good.

**Comment by soywiz** [comment]
I think i will have desktop internet access tomorrow. But i left my macbook and i just have a windows laptop to check. So if it is related to ios, i cannot test right now.
Can you reproduce the problem with a smaller project? Maybe from jtransc-examples so i can test? Have you tried lowering lime version? It canbe clang problem, haxe problem or our problem. If it is due to a large method, we can split it. But if it is related to haxe. Maybe the best solution is to generate haxe, thengenerate c++ and compile c++ and debug it to know whats happening

**Comment by SergeyLabutin** [comment]
test older lime versions: always same result

**Comment by SergeyLabutin** [comment]
If start stress test https://github.com/jtransc/jtransc-examples/pull/14 on iPad with 2K classes then get different error in runtime phase
```
Hi, my num is 2000 0
MyFileHandle: spineboy/spineboy.atlas
JTranscSyncIOLimeImpl.open: assets/spineboy/spineboy.atlas || /spineboy/spineboy.atlas in mode 1
libc++abi.dylib: terminating with uncaught exception of type Dynamic
(lldb) 
```
app running but in JNI.cpp `::z::JNC JNC_obj::yxk( ::z::EH p0,bool p1){`
I update lime to 5.1.0 and test again

**Comment by SergeyLabutin** [comment]
I test new lime with 2500 lines, same result.

**Comment by soywiz** [comment]
Hopefully I will have Internet today. So if it is the case I will check tonight, or this weekend. I know this is important to you, so I will try to do as much as possible

**Comment by SergeyLabutin** [comment]
Thanks, i make more tests, i think `libc++abi.dylib: terminating with uncaught exception of type Dynamic` not a problem, but related, i think main problem with count classes and big AllClasses, #168 working in java 5500K classes, but only 2500K works in JT.
P.S. Thanks for help it's really important for me.

**Comment by soywiz** [comment]
As far as I know there is no limit in java classes. But a single java class can have 64K methods. And each method 64kb in size. I think the method limitation is due to the class file format that uses uint16 to reference methods.

I will investigate ASAP. Also I will try to find online if clang imposes limits on structs or something. We cannot control that too much since haxe may create several structs per class (not validated) and increase total numbers of classes.

Also jtransc create classes when using java8 dynamicinvoke for lambdas. (That can be optimized per target) but the fallback is to create one haxe class per lambda internally.
I think that static fields and methods inside interfaces create additional classes in haxe

**Comment by soywiz** [comment]
BTW searching using google for this:
libc++abi.dylib: "terminating with uncaught exception of type Dynamic"

Yields to a couple of projects using haxe. So it seems to be haxe related. Maybe it is just that can't found some assets. Maybe I can add a try catch at the entry point. Here: https://github.com/jtransc/jtransc/blob/352a09a24100717b4b5e9981f3c0b7b722530def/jtransc-gen-haxe/src/com/jtransc/gen/haxe/HaxeTarget.kt#L415 print and then rethrow (to have more information about the uncatched exception)
also here too: https://github.com/jtransc/gdx-backend-jtransc/blob/b0728186676638e08054d0e77550ee5671869ff9/gdx-backend-jtransc/src/com/jtransc/media/limelibgdx/LimeApplication.java#L25 (if you are using lime, that's your main function)

**Comment by SergeyLabutin** [comment]
confirmed fixed, any big method throw EXC_BAD_ACCESS on iOs only.

**Comment by soywiz** [comment]
That's bad.

You can try to enable this on HaxeTarget. That would reduce method complexity with control flow.
```
//const val ENABLE_HXCPP_GOTO_HACK = true
const val ENABLE_HXCPP_GOTO_HACK = false // @TODO: If last statement is a goto. Add return null; or return; at the end
```

Also how big has to be the method? JTransc generated files are still that big?
If there is something I can do, just tell me.

**Comment by SergeyLabutin** [comment]
In JT all fine, but in my code i have 2 big functions, after fix this, same error on my code, i fix it write my code better, but other maybe confused, because haxecpp works good, and only iOs throw in runtime. But i think we close it and return after anybody get same problem.

**Comment by soywiz** [comment]
Great. It is a bit pain that ios fails in those cases at runtime instead of compile time. It is a relief that you managed to fix it.
