### ISSUE TITLE
Critical bug - big switch

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#206]
After add one JTranscKeep, i get stable crush `libc++abi.dylib: terminating with uncaught exception of type Dynamic` before it i get one time of 10 launches. I think JTranscKeep add in ProgramReflection one or more cases and function size again bigger than 64 KB.

@soywiz Can you add in JTransc mechanism for detect big functions and huge switches in compile time (not runtime)?
P.S. It's not my level =)

**Comment by soywiz** [comment]
Can you provide an example? (So i can use as test)
Also I cannot use 64K in size as an indicator since im not generating c++ direclty but haxe first in this case. I can use number of statements, nodes or other things.
You want me to just print a warning in this case or try to split it somehow?
This just happens inside ProgramReflection? Or outside it? Which method inside ProgramReflection is bigger than 64K?

**Comment by soywiz** [comment]
Maybe you can provide your ProgramReflection file with minimizeNames=true and searching for all ".*" and replacing with garbage so no confidential information is provided. I need some context or i wont be able to fix it

**Comment by SergeyLabutin** [comment]
```
 ::JA_L ProgramReflection__obj::getFieldAnnotations_II__Ljava_lang_annotation_Annotation_(int p0,int p1){
            	HX_GC_STACKFRAME(&_hx_pos_730ed619cd3a2627_1264_getFieldAnnotations_II__Ljava_lang_annotation_Annotation_)
```

14 800 lines

as example line
```
            			case (int)7984: {
HXLINE(10960)				if ((p1 == (int)33472)) {
```

**Comment by SergeyLabutin** [comment]
> Maybe you can provide your ProgramReflection file with minimizeNames=true and searching for all ".*" and replacing with garbage so no confidential information is provided. I need some context or i wont be able to fix it

I try provide need time for recompile

**Comment by soywiz** [comment]
Maybe i can create a method per class. But if you can provide an example file today, it will be easier for me, i will be able to work on it this evening

**Comment by SergeyLabutin** [comment]
[ZD.zip](https://github.com/jtransc/jtransc/files/1141903/ZD.zip)

provided ProgramReflection from ios target.

**Comment by soywiz** [comment]
Thanks! I will look at this this evening

**Comment by soywiz** [comment]
It seems that the main problem is here:
```
static  public   function hv/*getFieldAnnotations*/(p0:Int, p1:Int):JA_L {
```

That's the bigger function.

What I'm going to do first is this:

```
		out = new JA_L(1, "[Ljava.lang.annotation.Annotation;");
		out.set(0, (new z.LF()).i4(__str1, true));
		return out;
```

--->

```
return JA_L.create1("[Ljava.lang.annotation.Annotation;", (new z.LF()).i4(__str1, true));
```

Probably this will be enough for now.

But I can move each case for each class into a separate method. That would probably help since the number of methods a class can have is 64K I think. And probably you won't have classes with that many methods or fields.

**Comment by SergeyLabutin** [comment]
more than 64K methods we have on each project last 5 year =)). But i believe, for reflection we can have this limit =)

**Comment by soywiz** [comment]
I'm working on it. I almost have the first part. I will make a PR before going to sleep so you can test later or tomorrow.

**Comment by SergeyLabutin** [comment]
Thanks!

**Comment by SergeyLabutin** [comment]
@soywiz Have you progress?

**Comment by soywiz** [comment]
Not too much time. But this weekend i will have some time to fix it

**Comment by SergeyLabutin** [comment]
Thanks!
