### ISSUE TITLE
JTranscLibgdx and JTranscLime are not import-able from Java

### ISSUE THREAD

**Issue by tommyettinger** [jtransc/jtransc#30]
This is because they are in the default package, and this makes them unavailable for import without using reflection. I'm not sure why they lack a package in the first place; using the default package seems to be strongly discouraged by the Java recommendations because of this import impossibility issue.

**Comment by tommyettinger** [comment]
I'm not sure if this went to the right project, actually. There's a lot of mingling of code between Github projects here, it seems.

**Comment by soywiz** [comment]
I'm importing them just fine; at least with intelliJ. Which IDE are you using?

Anyway, I will put them in a package.

Don't worry too much about the repo for the issues, this one is fine.

**Comment by soywiz** [comment]
You should be able to import already (I have moved into packages and unified some old package names).

In order to get jtransc working from git you have to:
Download jtransc and jtransc-media.

You have to install first jtransc-rt-core and jtransc-rt in that order, there are a .bat and a .sh in the root folder:
https://github.com/jtransc/jtransc/blob/master/install_rt_and_core.bat
Then you can do a: `mvn install -DskipTests` first for jtransc and then for jtransc-media.

**Comment by tommyettinger** [comment]
I figured out a workaround in the meanwhile; if I use the default package in my Java files that import JTranscLibgdx and JTranscLime, my code sees those just fine, though I get a warning about using the default package. I think Kotlin is more flexible than Java about package conventions. I'm currently trying to port a LibGDX demo that uses ApplicationAdapter to JTransc, and I am probably missing something important. Is there any equivalent to the create(), render(), etc. overrides in ApplicationListener for JTranscGame? I see a different Stage and Sprite class than what I expect with those names in libGDX. I'm just not at all sure how to start porting libGDX code to JTransc.

**Comment by tommyettinger** [comment]
Following up on my last comment, I'm attempting to port an existing small-ish demo that depends on libGDX (and my library that depends on libGDX), and I'm not really sure how this should be translated: https://github.com/tommyettinger/SquidLib-Demos/blob/master/JTranscDemo/src/JTranscDemo.java#L152 (in the comments for `main`). It seems to need a JTransc Sprite object for the root, so should I assume any code that depends on libGDX classes needs to be rewritten to use JTransc's classes? So it can switch between libGDX and Lime for implementation? Is there some way (or could there be some way) to use the libGDX API and produce Lime, or are they not similar enough?

**Comment by soywiz** [comment]
If your project uses libgdx you should probably use this project instead:
https://github.com/jtransc/gdx-backend-jtransc/tree/master/gdx-backend-jtransc

This is a gdx backend using jtransc. (you should mvn install since it is not on central). Also it is a WIP, so not fully implemented.

The gdx cuboc demo using jtransc: https://github.com/jtransc/gdx-backend-jtransc/tree/master/cuboc-demo

If it doesnt work for you (methods not implemented or other stuff failing) I will check.

**Comment by tommyettinger** [comment]
That's great! I was wondering what the intended way to use JTransc was or would be soon, this looks like an excellent way to move existing code to get the advantages of JTransc. I'll give it a shot!

**Comment by tommyettinger** [comment]
It looks like the example pom.xml files use JTransc 0.1.5; will it load a newer version if the GDX backend is built from source? Does that need to be updated to 0.2.0, or is it fine to leave it where it is?

**Comment by soywiz** [comment]
We are using JTranscMedia because it does not use direct opengl calls and we have an optimized implementation that works on flash too without the whole libgdx overhead.

But if your project uses libgdx already the most straightforward way is to use that work-in-progres backend.

Yep, I probably didn't updated the pom.xml. You can change it to 0.2.0 and if it doesn't work try with 0.1.5. If it doesn't work to you, any feedback with that will be appreaciated. In that case if you could upload the project I could try to run and debug until it works.

**Comment by tommyettinger** [comment]
Well there's some progress. Using Cuboc with the 0.1.5 changed to 0.2.0, Haxe and Lime installed with up-to-date versions, old versions of Haxe uninstalled, and the .bat to build, it seems to get much closer. I haven't changed any code from the Cuboc JTransc example, I just updated the pom.xml files for the current version. When double-clicking MyApp.exe , generated in a subfolder of target/, I get this screen:

![image](https://cloud.githubusercontent.com/assets/160684/14842084/e0606950-0bf8-11e6-8f24-00acfce1722b.png)

It's totally different if I run MyApp.exe from the command line, however. With no args, and using an absolute path to the exe to run it:

![image](https://cloud.githubusercontent.com/assets/160684/14842120/3de1cff6-0bf9-11e6-9034-8dbfa1651700.png)

This responds to keyboard input (I pressed z twice here), prints an FPS log, and otherwise shows a black or possibly dark gray screen. My cmd.exe session is in the background. Messages from earlier include:

```
MyFileHandle: data/title.png
glTexImage2D:target=3553,level=0,internalformat=6408,width=512,height=512,border=0,format=6408,type=5121,pixels=1048576
[Cubocy] dispose main menu : null
MyFileHandle: data/intro.png
glTexImage2D:target=3553,level=0,internalformat=6408,width=512,height=512,border=0,format=6408,type=5121,pixels=1048576
[Cubocy] dispose intro : null
MyFileHandle: data/levels.png
MyFileHandle: data/tile.png
glTexImage2D:target=3553,level=0,internalformat=6408,width=32,height=32,border=0,format=6408,type=5121,pixels=4096
MyFileHandle: data/bob.png
glTexImage2D:target=3553,level=0,internalformat=6408,width=128,height=128,border=0,format=6408,type=5121,pixels=65536
[Cubocy] blocks created : null
MyFileHandle: data/controls.png
glTexImage2D:target=3553,level=0,internalformat=6408,width=256,height=256,border=0,format=6408,type=5121,pixels=262144
```

I'm not sure if this is the expected output, particularly the " : null" repeated in a few lines. I'll try what I can to get the Cuboc demo working before I move on to porting my own stuff.

**Comment by tommyettinger** [comment]
I could rebuild and make a Gist of the build log if it would help. The first time I tried it, a bad installation of haxelib stopped the build when it tried to run hxcpp, but after much of the Java part of the build had completed. It's possible `mvn clean` didn't get rid of some leftover files.

**Comment by soywiz** [comment]
There is a jtransc.js.pom.xml that generates a javascript version. That version works for you? I just tried that one lately and not the c++ one (you will have to run a web server in the output folder instead of just open the index.html due to security reasons). I will check the c++ one today.

**Comment by tommyettinger** [comment]
JS works 100%. I tested it with the simple web server that comes with Python. If there's anything I can do to help debug the C++, give the word!
