### ISSUE TITLE
Scala to Dart

### ISSUE THREAD

**Issue by shafqatevo** [jtransc/jtransc#300]
Hi,

Amazing tool, thanks @soywiz !

How good is the Scala to Dart transpiling end result with this?

Thanks!

**Comment by soywiz** [comment]
IIRC in the latest versions I did an optimization to do all the static initialization at the beginning of the program instead of on request to improve runtime performance, that worked fine for Java and Kotlin, but the Scala version I tried later seemed to had problems and determining the initialization order at compile-time was not right. Also I'm not actively developing this project at this point, though I could accept PRs.

Scala provides metaprogramming and ways to obtain the AST. AFAIK Scala.JS uses that mechanism to generate its output. You could do the same for Dart using Scala.JS as reference, or use an untyped Scala.JS -> Javascript -> Dart chain of transpilers.

**Comment by shafqatevo** [comment]
@soywiz thanks for the great insights!

**Comment by layinka** [comment]
Please do you have a sample/guide for using this to convert scala to Haxe?

**Comment by soywiz** [comment]
@layinka the project don't have such guide and Scala is unsupported on latests versions. Right now the project is being worked on at a slower pace and the focus shift to Java/Kotlin and a reduced number of targets covering specific use-cases for my other project needs.
I have update the description of the project to not state Scala being supported.
