### ISSUE TITLE
Java to Julia transpiler

### ISSUE THREAD

**Issue by mkschulze** [jtransc/jtransc#306]
Hi,

this would be a great addition to the tool I think. Would that be possible maybe?

**Comment by soywiz** [comment]
It could be possible. Unfortunately I'm not expending too much time myself on this and my main focus would be to keep and maintain only a few specific targets to create final executables (instead of libraries for consuming in other languages) to target as much platforms as possible: C++, C#, JavaScript and maybe Dart.

I would have to check the documentation/README other stuff to be sure this new focus is reflected.

Still you can fork the project, choose the closest target you can find in terms of syntax and try to modify it to output something that compiles on Julia. But unfortunately I won't do that myself, sorry.

Good luck with that in the case you do it yourself in a fork!
