### ISSUE TITLE
Build currently failing due to Central version; consider JitPack?

### ISSUE THREAD

**Issue by tommyettinger** [jtransc/jtransc#32]
This is just a suggestion, but...

I've started using [JitPack](https://jitpack.io/) (a Maven-Central-like jar repository that builds GitHub releases of Maven, Gradle, and other projects whenever someone depends on them, and also allows building and depending on individual commits) often for my Java code, and it seems to be holding up well. The build status on Travis CI currently seems to be failing due to 0.2.1 not yet being uploaded to Maven Central, and I know some of the Central requirements are annoying and time-consuming. At least during development, maybe you could try changing the dependencies of projects to JitPack? 0.2.1 is ready to build once a project depends on it and requests it from JitPack, since there's a GitHub release; see this for more https://jitpack.io/#jtransc/jtransc/0.2.1 .Central doesn't allow other repositories to be used on projects hosted on their repository, but you could switch out the JitPack repository for Central if you have a stable build you want available via the standard way.

Only downside is, the first person to request a version or commit needs to wait for the project to build, and if any of the Maven projects depend on Haxe to complete a `mvn install` step (without running tests), there probably won't be any way for JitPack to build each release. Although, Travis CI seems to be doing fine, and I don't know if it has Haxe installed. If you log in to JitPack with your GitHub account, you can tell JitPack to try to build a release or commit early, in case you want a release to build "in the background" and then be available to other projects when they request it in a few minutes.

I don't know if this is a valid suggestion for this particular project, but I think it might help ease the hassle of releasing.

**Comment by soywiz** [comment]
I will check JitPack.

Since I'm installing `jtransc-rt-core` and `jtransc-rt` before the proper installing (because I'm using JAR files from `.m2` folder in jtransc) I thought it would work. But it seems that jtransc-rt-core has jtransc as its parent and it seems to fail there).

I should try to relax the requirement of installing rt and rt-core before. Maybe tests could use target folder with class files instead of jar files from the m2 folder. Because packaging+installing happens after test have passed.

This repo should not have dependencies (aside from kotlin, asm and junit).

And you are right that central is pretty picky and time consuming. And I didn't know about JitPack, and seems pretty cool :) I will try. Probably with https://github.com/jtransc/gdx-backend-jtransc and other projects.

---

BTW: Theee days I had several meetings and I had to work on other stuff. Now I'm again with jtransc and probably will work on it a bit this weekend. I'm going to fix this first and later I will check the gdx opengl c++ problem. It seemed that it was working, but nothing was shown. I will have to locate a opengl debugger or something, it will probably take some time. Did you find out something about it?

**Comment by tommyettinger** [comment]
Ah, sorry for the late reply. I was just looking for open source ahead-of-time compilers for Java code, somehow it slipped my mind that JTransc does that too. In fact, other than GCJ, which is compatible only with Java 1.5 (maybe not even that?), there's almost no projects that do this kind of work. It seems like you've found an excellent way to reuse the stable, proven Haxe compiler for what would otherwise seem like mad science; targeting "every platform ever" with Java is not something even existing commercial tools do (i.e. Excelsior JET).

I'll try to build and run the C++ GDX demo again. Does hxcpp cache pre-built standard library files? The first build took a very long time to even get to an error. I'll clean the project anyway to ensure nothing old and broken gets used again.

**Comment by soywiz** [comment]
Yeah. There is no other opensource multitarget aot for jvm as far as I know.

Last version of jtransc (without minimized names) should reuse files between hxcpp compilations. Previously adding/removing methods caused everyhting to compile again. Due to method ids changing for every method in every class. Now method ids are local to classes. Also release builds and debug builds with lime are in different folders now. So changing release type do not trigger everything to recompile.

Haxe 3.2 has a bug in c++ target that I trigger in some cases. Not sure if it was in Java Std or Kotlin Std related to inheritance. It doesnt happen in other targets. You will have to use Haxe 3.3. That means nightlies until they release 3.3Rc1, which I expect they release soon. I can assist you getting it in the mean time.

I have to check wether gdx backend is updated to the lastest git version.

**Comment by soywiz** [comment]
Sometime ago we were evaluating options:

* Using KotlinJs to target js everywhere and use Apache Cordova for mobile. KotlinJs was not too much mature by then, and didn't provide the reflect capabilities we needed. Also that was not allowing us to target to flash to do some integrations.
* Native for Android + TeaVM for JS + RoboVM for iOS + totally ignore WP and flash. TeaVM is just a great piece of software, but it has a metaprogramming approach instead of reflection and it is focused on javascript. We wanted reflection, and have several targets. For peace of mind to avoid another huge rewrite of everything. Didn't want to depend on RoboVM (which turned to be a right decision). So we ended discarding that option too.
* Not using Kotlin at all. Kotlin is one of the most productive language to date and allowed us to share code with our extensive backend server that we were not going to change.

So creating JTransc was the best option.

**Comment by soywiz** [comment]
Since builds/tests are fixed and are already self-contained and not depending on maven. I'm going to close this.
Thanks for the JitPack suggestion. I know a couple of sites I'm going to use it (for example here https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-libgdx ) :) But I think it is not required for jtransc anymore.
